name: Create Releasable Package Drop

on:
  push:
    branches:
      - release-*

permissions:
  contents: read

# Ensure scripts are run with pipefail. See:
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#exit-codes-and-error-action-preference
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3
      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
      - run: |
          npm --version
          # corepack enable npm
          npm install -g $(jq -r '.packageManager' < package.json)
          npm --version
      - name: npm install and test
        run: |
          npm ci
          npm test
      - name: Installing browsers
        run: npx playwright install --with-deps
      - name: Validate the browser can import TypeScript
        run: npx hereby test-browser-integration
      - name: LKG, clean, and pack
        run: |
          npx hereby LKG
          npx hereby clean
          npm pack ./
          mv typescript-*.tgz typescript.tgz
      - name: Upload built tarfile
        uses: actions/upload-artifact@1746f4ab65b179e0ea60a494b83293b640dd5bba # v4.3.2
        with:
          name: tgz
          path: typescript.tgz
